#!/bin/sh
# bosco_add_host: Used to install ssh keys and blahp on remote hosts.

# 
# Arguments:
# $1 - fqdn hostname of remote host to install ssh keys
#

# Remote host to connect
remote_host=$1

# Bosco key location
bosco_key=$HOME/.ssh/bosco_key.rsa


# If the key doesn't exist, create it
if [ ! -e $bosco_key ]; then
    ssh-keygen -q -t rsa -f $bosco_key
fi


# Transfer the public key to the remote host
# ssh-copy-id is available on el5 from openssh-clients
ssh-copy-id -i $bosco_key $remote_host


# Copy blahp

# First, find the blahp
glite_location=`condor_config_val GLITE_LOCATION`

# Copy over blahp
rsync -av -e "ssh -i $bosco_key" $glite_location $remote_host:bosco/

